# Generated by Django 6.0.3 on 2026-04-03 20:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('kind', models.CharField(choices=[('chat', 'Chat'), ('report', 'Report')], max_length=16)),
                ('model', models.CharField(blank=True, max_length=128)),
                ('district', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('tone', models.CharField(blank=True, max_length=32)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutopilotDecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('token', models.CharField(blank=True, max_length=128)),
                ('selected_district', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('refresh_bucket', models.IntegerField(default=0)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-decision_at'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryPacket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('selected_district', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('active_scenario', models.CharField(blank=True, max_length=64, null=True)),
                ('alert_count', models.PositiveIntegerField(default=0)),
                ('auto_districts', models.PositiveIntegerField(default=0)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
