# Generated by Django 6.0.3 on 2026-04-03 20:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrypacket',
            name='selected_page',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='telemetrypacket',
            name='session_access',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='telemetrypacket',
            name='session_role',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='telemetrypacket',
            name='token',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('district', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('severity', models.CharField(blank=True, db_index=True, max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metric', models.CharField(blank=True, max_length=128)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('action', models.TextField(blank=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_events', to='api.telemetrypacket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DistrictCycleSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('district', models.CharField(db_index=True, max_length=128)),
                ('scenario', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('tone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('risk_score', models.PositiveIntegerField(default=0)),
                ('resilience', models.PositiveIntegerField(default=0)),
                ('response_readiness', models.PositiveIntegerField(default=0)),
                ('pressure', models.FloatField(default=0)),
                ('quality', models.PositiveIntegerField(default=0)),
                ('coverage', models.PositiveIntegerField(default=0)),
                ('complaints', models.PositiveIntegerField(default=0)),
                ('incidents', models.PositiveIntegerField(default=0)),
                ('response_eta', models.PositiveIntegerField(default=0)),
                ('pump_load', models.PositiveIntegerField(default=0)),
                ('consumption', models.PositiveIntegerField(default=0)),
                ('active_signals', models.PositiveIntegerField(default=0)),
                ('critical_signals', models.PositiveIntegerField(default=0)),
                ('action_count', models.PositiveIntegerField(default=0)),
                ('monitored_from', models.CharField(blank=True, max_length=128)),
                ('snapshot_payload', models.JSONField(default=dict)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_frames', to='api.telemetrypacket')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
